enum MatchState @entity {
  Future
  Current
  Finished
  Error
}

enum Team {
  Team1
  Team2
}

type Match @entity {
  id: ID!
  game: String!
  date_timestamp: BigInt!
  date_string: String!
  team_1: String!
  team_2: String!
  team_1_total_bets: BigInt!
  team_2_total_bets: BigInt!
  match_state: MatchState!
  winner: Team
  created_at: BigInt!
}

enum PayState {
  Paid
  RefundPaid
}

type Bet @entity {
  id: ID!
  account_id: String!
  amount: BigInt!
  match_id: String!
  team: Team!
  potential_winnings: BigInt!
  pay_state: PayState
  created_at: BigInt!
}

type User @entity {
  id: ID!
  total_winnings: BigInt!
  stake_in: BigInt!
  unstaked: BigInt!
  number_of_wins: Int!
}

type WinningEvent @entity(timeseries: true) {
  id: Int8!
  timestamp: Timestamp!
  user: String!
  amount: BigInt!
}

type UserWinningStats
  @aggregation(intervals: ["hour", "day"], source: "WinningEvent") {
  id: Int8!
  timestamp: Timestamp!
  user: String!
  totalWinnings: BigInt! @aggregate(fn: "sum", arg: "amount")
  numberOfWins: Int! @aggregate(fn: "count")
}
