enum MatchState @entity {
  Future
  Current
  Finished
  Error
}

enum Team {
  Team1
  Team2
}

type Match @entity {
  id: ID!
  game: String!
  date: BigInt!
  team_1: String!
  team_2: String!
  team_1_total_bets: BigInt!
  team_2_total_bets: BigInt!
  match_state: MatchState!
  winner: Team
  created_at: BigInt!
}

enum PayState {
  Paid
  RefundPaid
}

type Bet @entity {
  id: ID!
  account_id: String!
  amount: BigInt!
  match_id: ID!
  team: Team!
  potential_winnings: BigInt!
  pay_state: PayState
  created_at: BigInt!
}